### PR TITLE
Listenbrainz fixes

### LINKED ISSUE #385: Listens successfully scrobbled to ListenBrainz remain in cache
I think this is because sls expects a response beginning with `success` [here](https://github.com/tgwizard/sls/blob/d7ab95f7bbaa6f654ab5c7147c3198e13feaed8f/app/src/main/java/com/adam/aslfms/service/Scrobbler.java#L312) but the LB api has changed to returning json with our new Beta release. (https://github.com/metabrainz/listenbrainz-server/blob/master/listenbrainz/webserver/views/api.py#L75)

### PR DESCRIPTION
**Pull request by 19379**
Since the LB server went in to beta, the app doesn't recognise the updated response from a successful listen and continuously caches/retries when there is no need. Should fix #385 

Also, don't send "listened_at" with "playing_now" requests as this causes the server to return a 400 bad request error. This isn't documented and I've mentioned it over on the LB issues system...

https://tickets.metabrainz.org/projects/LB/issues/LB-206

### CODE REVIEW

**Comment by HumbleBeeBumbleBee** [comment]
Wow @19379  this is beautiful. Saved me some time for sure!

**Comment by HumbleBeeBumbleBee** [comment]
I will test this ASAP.

File: app/src/main/java/com/adam/aslfms/service/Scrobbler.java [hunk 1]
```diff
@@ -304,16 +304,21 @@ public void scrobbleCommit(HandshakeResult hInfo, Track[] tracks)
                 Log.d(TAG, response);
                 if (resCode == 401) {
                     settings.setListenBrainzToken(netApp, "");
-                    throw new BadSessionException("Now Playing failed because of badsession");
+                    throw new BadSessionException("Listenbrainz submission failed because of bad token.");
```
Comment (Freso) [inline app/src/main/java/com/adam/aslfms/service/Scrobbler.java]: "ListenBrainz", not "Listenbrainz", please. I already made a PR to fix all instances of the lowercase 'b' once, please don't introduce new ones. 😢

File: app/src/main/java/com/adam/aslfms/service/NPNotifier.java [hunk 2]
```diff
@@ -210,8 +210,7 @@ public void notifyNowPlaying(Track track, HandshakeResult hInfo)
                 JSONObject baseObj = new JSONObject();
                 baseObj.put("listen_type", "playing_now");
                 JSONObject trackInfo = new JSONObject();
-                trackInfo.put("listened_at", Long.toString(track.getWhen()));
-
+
```
Comment (Freso) [inline app/src/main/java/com/adam/aslfms/service/NPNotifier.java]: Random whitespace makes me sad. :(

**Comment by paramsingh** [comment]
Sorry if this is impatient, but any ETA on when we could see this PR in a release?

**Comment by 19379** [comment]
https://github.com/tgwizard/sls/releases

File: app/src/main/java/com/adam/aslfms/service/NPNotifier.java (hunk 2 above)
Comment (19379) [reply app/src/main/java/com/adam/aslfms/service/NPNotifier.java]: https://github.com/tgwizard/sls/pull/395

**Comment by Freso** [comment]
Doesn't seem to have hit F‐Droid yet though: https://f-droid.org/packages/com.adam.aslfms/ – I wonder if there's some way to get them to pull the newer code. 🤔

**Comment by HumbleBeeBumbleBee** [comment]
Hi @paramsingh it's been released. It was definitely rushed because I'm currently really busy.
If somebody else feels responsible enough to be a major contributor with releases etcetera and has the free time, please contact @ tgwizard.

I don't think those two small errors are the end of the world. Code works and the message is communicated to the user.
Please make a pull request to current code if you want changes.

**Comment by Freso** [comment]
I made an issue for F-Droid to get the 1.5.6 version: https://gitlab.com/fdroid/fdroiddata/issues/889
